#!/bin/bash -ex
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

# service id:  ${serviceId}
# stage: ${stage}
L_STATUS=0

if [ "$G_STATUS" = "1" ]; then
    return 1
fi;

TOTAL_STEPS=$((TOTAL_STEPS+1))

export CTX=${serviceId}:${stage}-tool

. shared

prolog $CTX

<#list dirs as dir>
mkdirp ${dir}
</#list>

r <#list params as param><#if param_index != 0>      </#if>${param} <#if param_index = 0>$TOOL_JAVA_OPTS </#if><#if param_has_next>\</#if>
</#list>

